export interface PaperConfig {
  id: string
  title: string
  subtitle: string
  abstract: string
  pdfUrl: string
  latexUrl?: string
  githubUrl: string
  date: string
  authors: string[]
  tags: string[]
  relatedLinks?: {
    label: string
    url: string
  }[]
}

export interface SiteConfig {
  name: string
  fullName: string
  description: string
  website: string
  github: string
  primaryColor: string
  secondaryColor: string
  accentColor: string
  logo: string
  papers: PaperConfig[]
}

export const siteConfig: SiteConfig = {
  name: 'Pars Network',
  fullName: 'Pars DAO',
  description: 'Censorship-resistant communication and governance infrastructure for the Persian diaspora',
  website: 'https://pars.network',
  github: 'https://github.com/parsdao',
  primaryColor: '#E8B931',
  secondaryColor: '#1B4332',
  accentColor: '#FF6B6B',
  logo: '/logos/pars-logo.svg',
  papers: [
    {
      id: 'whitepaper',
      title: 'Pars Network Whitepaper',
      subtitle: 'Censorship-Resistant Infrastructure for the Persian Diaspora',
      abstract: 'Comprehensive whitepaper describing censorship-resistant infrastructure for the Persian diaspora community.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-whitepaper.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-whitepaper.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Whitepaper', 'Infrastructure', 'Censorship Resistance'],
    },
    {
      id: 'network-whitepaper',
      title: 'Pars Network Architecture',
      subtitle: 'Dual-Layer Protocol Design',
      abstract: 'Dual-layer protocol architecture for the Pars Network with EVM L2 and session daemon integration.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-network-whitepaper.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-network-whitepaper.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Architecture', 'Protocol', 'Network Design'],
    },
    {
      id: 'dual-layer',
      title: 'Dual-Layer Architecture',
      subtitle: 'EVM L2 and Session Daemon Integration',
      abstract: 'Dual-layer architecture combining EVM L2 with session daemon for censorship-resistant operations.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-dual-layer.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-dual-layer.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Dual-Layer', 'EVM', 'L2', 'Session Daemon'],
    },
    {
      id: 'mesh-networking',
      title: 'Mesh Networking Protocol',
      subtitle: 'Peer-to-Peer Communication Under Censorship',
      abstract: 'Mesh networking protocol for peer-to-peer communication in censored environments.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-mesh-networking.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-mesh-networking.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Mesh', 'P2P', 'Networking', 'Censorship'],
    },
    {
      id: 'session-protocol',
      title: 'Session Protocol',
      subtitle: 'End-to-End Encrypted Communication Layer',
      abstract: 'End-to-end encrypted communication protocol for secure messaging in the Pars Network.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-session-protocol.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-session-protocol.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Session', 'E2E Encryption', 'Communication'],
    },
    {
      id: 'post-quantum',
      title: 'Post-Quantum Cryptography for Pars',
      subtitle: 'Quantum-Resistant Security Primitives',
      abstract: 'Post-quantum cryptographic primitives for quantum-resistant security in the Pars Network.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-post-quantum.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-post-quantum.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Post-Quantum', 'Cryptography', 'Security'],
    },
    {
      id: 'coercion-resistance',
      title: 'Coercion-Resistant Governance',
      subtitle: 'Protecting Voters from External Pressure',
      abstract: 'Governance protocol protecting voters from coercion and external pressure in adversarial environments.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-coercion-resistance.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-coercion-resistance.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Governance', 'Coercion Resistance', 'Voting'],
    },
    {
      id: 'zk-identity',
      title: 'Zero-Knowledge Identity',
      subtitle: 'Privacy-Preserving Identity Verification',
      abstract: 'Zero-knowledge identity verification for privacy-preserving authentication in the Pars Network.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-zk-identity.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-zk-identity.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['ZK', 'Identity', 'Privacy', 'Verification'],
    },
    {
      id: 'stealth-addresses',
      title: 'Stealth Address Protocol',
      subtitle: 'Unlinkable Transaction Destinations',
      abstract: 'Stealth address protocol for unlinkable transaction destinations and financial privacy.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-stealth-addresses.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-stealth-addresses.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Stealth Addresses', 'Privacy', 'Transactions'],
    },
    {
      id: 'did-standard',
      title: 'Pars DID Standard',
      subtitle: 'Decentralized Identifiers for Pars Network',
      abstract: 'Decentralized identifier standard for self-sovereign identity on the Pars Network.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-did-standard.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-did-standard.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['DID', 'Identity', 'Decentralized', 'Standard'],
    },
    {
      id: 'social-recovery',
      title: 'Social Recovery Protocol',
      subtitle: 'Guardian-Based Account Recovery',
      abstract: 'Social recovery protocol with guardian-based account recovery for secure key management.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-social-recovery.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-social-recovery.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Social Recovery', 'Guardians', 'Account Recovery'],
    },
    {
      id: 'e2e-messaging',
      title: 'End-to-End Encrypted Messaging',
      subtitle: 'Signal Protocol Adaptation for Decentralized Networks',
      abstract: 'Signal Protocol adaptation for end-to-end encrypted messaging on decentralized networks.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-e2e-messaging.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-e2e-messaging.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['E2E', 'Messaging', 'Encryption', 'Signal Protocol'],
    },
    {
      id: 'persian-nlp',
      title: 'Persian NLP Infrastructure',
      subtitle: 'Natural Language Processing for Farsi',
      abstract: 'Natural language processing infrastructure for Farsi and Persian language AI applications.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-persian-nlp.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-persian-nlp.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['NLP', 'Persian', 'Farsi', 'Language'],
    },
    {
      id: 'federated-learning',
      title: 'Federated Learning for Persian AI',
      subtitle: 'Distributed Training for Low-Resource Languages',
      abstract: 'Federated learning for distributed training of Persian AI models in low-resource language settings.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-federated-learning.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-federated-learning.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Federated Learning', 'Persian', 'Distributed Training'],
    },
    {
      id: 'distributed-inference',
      title: 'Distributed Inference Protocol',
      subtitle: 'Decentralized AI Inference for Censored Regions',
      abstract: 'Distributed inference protocol for decentralized AI inference in censored regions.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-distributed-inference.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-distributed-inference.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Inference', 'Distributed', 'Decentralized', 'AI'],
    },
    {
      id: 'diaspora-bridge',
      title: 'Diaspora Bridge Protocol',
      subtitle: 'Cross-Border Financial Infrastructure',
      abstract: 'Cross-border financial infrastructure for the Persian diaspora community.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-diaspora-bridge.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-diaspora-bridge.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Bridge', 'Cross-Border', 'Finance', 'Diaspora'],
    },
    {
      id: 'dao-governance',
      title: 'Pars DAO Governance',
      subtitle: 'Democratic Governance for Diaspora Communities',
      abstract: 'Democratic governance framework for diaspora communities with coercion-resistant voting.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-dao-governance.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-dao-governance.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['DAO', 'Governance', 'Democracy', 'Community'],
    },
    {
      id: 'veasha-tokenomics',
      title: 'Veasha Tokenomics',
      subtitle: 'Token Economics for Community-Owned Infrastructure',
      abstract: 'Token economics for community-owned infrastructure in the Pars Network.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-veasha-tokenomics.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-veasha-tokenomics.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Tokenomics', 'Veasha', 'Community', 'Economics'],
    },
    {
      id: 'cultural-archives',
      title: 'Decentralized Cultural Archives',
      subtitle: 'Permanent Storage for Persian Cultural Heritage',
      abstract: 'Decentralized permanent storage for Persian cultural heritage preservation.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-cultural-archives.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-cultural-archives.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Archives', 'Culture', 'Heritage', 'Storage'],
    },
    {
      id: 'shadow-governance',
      title: 'Shadow Governance Protocol',
      subtitle: 'Governance Under Authoritarian Regimes',
      abstract: 'Shadow governance protocol enabling democratic participation under authoritarian regimes.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-shadow-governance.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-shadow-governance.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Governance', 'Shadow', 'Censorship Resistance'],
    },
    {
      id: 'asha-reserve',
      title: 'Asha Reserve Protocol',
      subtitle: 'Stablecoin Reserve for Diaspora Economics',
      abstract: 'Stablecoin reserve protocol for diaspora economics and cross-border value transfer.',
      pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-asha-reserve.pdf',
      latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-asha-reserve.tex',
      githubUrl: 'https://github.com/parsdao/papers',
      date: '2025-02-20',
      authors: ['Pars DAO'],
      tags: ['Stablecoin', 'Reserve', 'Economics', 'Asha'],
    },
  ],
}
